# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4f4c4733-6355-4685-b121-f4ffb81f0b01'
  imageRepository: 'testingcrudapp'
  containerRegistry: 'cloudcompapptest.azurecr.io'
  dockerfilePath: '**/Dockerfile-mysql'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cloudcompapptest'
        repository: 'phonebook-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile-app'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'cloudcompapptest'
        repository: 'phonebook-mysql'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile-mysql'
        tags: |
          $(Build.BuildId)
          latest
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure for Students (e43f1ee2-916b-4e66-b8df-d26a7307ff58)'
        appName: 'flaskcrudapp'
        containers: |
          cloudcompapptest.azurecr.io/phonebook-app:latest
          cloudcompapptest.azurecr.io/phonebook-mysql:latest
        multicontainerConfigFile: '**/docker-compose.yaml'
      
    


    
