version: '3.3'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    image: phonebook-mysql:latest
    restart: always

  phonebook-app:
    container_name: phonebook-app
    image: phonebook-app:latest
    depends_on:
      - phonebook-mysql
    restart: always
