version: '3.3'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    image: cloudcompapptest.azurecr.io/phonebook-mysql:latest
    restart: always

  phonebook-app:
    container_name: phonebook-app
    image: cloudcompapptest.azurecr.io/phonebook-app:latest
    depends_on:
      - phonebook-mysql
    ports:
      - "8080:80"
    restart: always
